FROM python:3.12-slim
WORKDIR /app

# Сразу переходим к копированию и установке pip
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
ENTRYPOINT []
CMD ["uvicorn", "target_apps.mock_bot:app", "--host", "0.0.0.0", "--port", "8000"]