services:
  # 1. База данных
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: knowledge_base
    ports:
      - "5432:5432"
    healthcheck:
      # Проверка, что база реально готова принимать соединения
      test: [ "CMD-SHELL", "pg_isready -U user -d knowledge_base" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Бот с ИИ
  bank-bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: bank_bot_container
    ports:
      - "8000:8000"
    restart: always
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/knowledge_base
      # ВАЖНО: Тест внутри бота должен стучать в 127.0.0.1 (себя)
      - TARGET_URL=http://127.0.0.1:8000
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4G
    depends_on:
      db:
        condition: service_healthy # Ждем не просто старта, а готовности базы

  # 3. Нагрузочный тестер (Locust)
  locust-master:
    build:
      context: .
      dockerfile: Dockerfile.locust
    container_name: locust_master
    ports:
      - "8089:8089"
    volumes:
      - .:/mnt/locust
    # Мастер говорит воркерам стучать в bank-bot по имени сервиса
    command: -f /mnt/locust/locustfile.py --master --host http://bank-bot:8000
    depends_on:
      - bank-bot

  locust-worker:
    build:
      context: .
      dockerfile: Dockerfile.locust
    volumes:
      - .:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host locust-master
    depends_on:
      - locust-master

volumes:
  postgres_data:
