services:
  bank-bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: bank_bot_container
    ports:
      - "8000:8000"
    volumes:
      - ./scenarios:/app/scenarios
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G

  locust:
    build:
      context: .
      dockerfile: Dockerfile.locust
    container_name: locust_container
    ports:
      - "8089:8089"
    volumes:
      - .:/mnt/locust
    command: -f /mnt/locust/locustfile.py --host http://bank-bot:8000
    depends_on:
      - bank-bot
