FROM python:3.10-slim
WORKDIR /app
RUN apt-get update && apt-get install -y libpq-dev build-essential
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
# Запускаем 4 воркера прямо здесь
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "4"]